import Vue from "vue";

/** Forms/Fields **/
import CheckboxField from "./CheckboxField/CheckboxField.vue";
import CheckboxesField from "./CheckboxesField/CheckboxesField.vue";
import DateField from "./DateField/DateField.vue";
import DatetimeField from "./DatetimeField/DatetimeField.vue";
import EmailField from "./EmailField/EmailField.vue";
import HeadlineField from "./HeadlineField/HeadlineField.vue";
import InfoField from "./InfoField/InfoField.vue";
import LineField from "./LineField/LineField.vue";
import NumberField from "./NumberField/NumberField.vue";
import PasswordField from "./PasswordField/PasswordField.vue";
import RadioField from "./RadioField/RadioField.vue";
import RangeField from "./RangeField/RangeField.vue";
import SelectField from "./SelectField/SelectField.vue";
import TagsField from "./TagsField/TagsField.vue";
import TelField from "./TelField/TelField.vue";
import TextareaField from "./TextareaField/TextareaField.vue";
import TextField from "./TextField/TextField.vue";
import TimeField from "./TimeField/TimeField.vue";
import ToggleField from "./ToggleField/ToggleField.vue";
import UrlField from "./UrlField/UrlField.vue";

Vue.component("kirby-checkbox-field", CheckboxField);
Vue.component("kirby-checkboxes-field", CheckboxesField);
Vue.component("kirby-date-field", DateField);
Vue.component("kirby-datetime-field", DatetimeField);
Vue.component("kirby-email-field", EmailField);
Vue.component("kirby-headline-field", HeadlineField);
Vue.component("kirby-info-field", InfoField);
Vue.component("kirby-line-field", LineField);
Vue.component("kirby-number-field", NumberField);
Vue.component("kirby-password-field", PasswordField);
Vue.component("kirby-radio-field", RadioField);
Vue.component("kirby-range-field", RangeField);
Vue.component("kirby-select-field", SelectField);
Vue.component("kirby-tags-field", TagsField);
Vue.component("kirby-tel-field", TelField);
Vue.component("kirby-textarea-field", TextareaField);
Vue.component("kirby-text-field", TextField);
Vue.component("kirby-time-field", TimeField);
Vue.component("kirby-toggle-field", ToggleField);
Vue.component("kirby-url-field", UrlField);
